---

  - command: puppet config set server {{ certname }} --section main
  - command: puppet config set certname {{ certname }} --section main
  - command: puppet config set dns_alt_names {{ dns_alt_names }} --section main
  - command: puppet config set environment puppet --section main
  - command: puppet master --verbose
  - command: sleep 10
  - command: puppet agent -t
  - command: pkill -f 'puppet master --verbose'
