---

  - name: fetch puppetlabs el rpm
    get_url: url=http://yum.puppetlabs.com/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm dest=/tmp
  - name: install puppetlabs el rpm
    yum: name="/tmp/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm" state=installed
  - name: install puppet-server package
    yum: name=puppet-server state=installed
